#!/bin/bash

if [ -z $1 ]
then
    echo "Usage: $0 (loopback name)"
    echo "e.g.   $0 loopback"
    exit
fi

pactl load-module module-null-sink media.class=Audio/Source/Virtual sink_name=$1 channel_map=front-left,front-right
